name: amadeus-ex-machina
channels:
  - defaults
dependencies:
  - python==3.11
  - numpy
  - pyyaml
  - matplotlib
  - jupyter
  - pytest
  - pytorch
  - torchvision
  - black
  - pandas
  - pip
  - pip:
      - jams
      - mido
