name: amadeus-ex-machina
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python==3.11
  - pytorch=2.5.1
  - cudatoolkit=11.8
  - torchaudio
  - numpy
  - pyyaml
  - matplotlib
  - jupyter
  - pytest
  - black
  - pandas
  - scipy
  - scikit-learn
  - joblib
  - tqdm
  - pip
  - pip:
      - librosa
      - jams
      - mido
      - gdown
      - tinysoundfont
      - optuna
      - mirdata
      - yt_dlp
      - mir_eval
      - plotly
      - tqdm-joblib
