name: amadeus-ex-machina
channels:
  - defaults
dependencies:
  - python==3.11
  - numpy
  - pyyaml
  - matplotlib
  - jupyter
  - pytest
  - pytorch
  - torchvision
  - black
  - pandas
  - scipy
  - scikit-learn
  - joblib
  - tqdm
  - optuna
  - pip
  - pip:
      - torchaudio
      - librosa
      - jams
      - mido
      - gdown
      - tinysoundfont