name: amadeus-ex-machina
channels:
  - defaults
dependencies:
  - python==3.12
  - numpy
  - pyyaml
  - matplotlib
  - jupyter
  - pytest
  - black
  - pytorch
  - torchvision
  - pip
  - pip:
    - torchaudio
